name: avataaar_image
description: Flutter wrapper widget for Avataaars API allowing to generate and display avatar images.
version: 1.0.5
author: Tomasz Wyrowinski <tomwyr@hotmail.com>
homepage: https://github.com/tomwyr/avataaar-image/

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^0.8.0
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
